from django.urls import path, include
from . import views

urlpatterns=[
    path('/', views.index, name="index"),
    path('/new', views.new, name="new"),
    path('/new/j/<int:journey_id>/', views.newJourneyDomino, name="newJourneyDomino"),
    path('/newjourney', views.newjourney, name="newjourney"),
    path('/updatejourney/<int:journey_id>', views.updatejourney, name="updatejourney"),
    path('/journey/<int:journey_id>', views.journey, name="journey"),
    path('/journey/delete/<int:journey_id>', views.journeyDelete, name="journeyDelete"),
    path('/delete/<int:delete_id>', views.delete, name="delete"),
    path('/delete/j/<int:journey_id>/f/<int:domino_id>/', views.deleteJourneyDomino, name='deleteJourneyDomino'),
    path('/id/<int:domino_id>/', views.domino, name='domino'),
    path('/new/<int:domino_id>/', views.newsub, name='newsub'),
    path('/pin/<int:domino_id>/', views.pin, name='pin'),
    path('/pin/p/<int:domino_id>/', views.pinParent, name='pinParent'),
    path('/pin/h/<int:domino_id>/', views.pinHome, name='pinHome'),
    path('/pin/j/<int:journey_id>/f/<int:domino_id>/', views.pinJourney, name='pinJourney'),
    path('/complete/<int:domino_id>/', views.complete, name='complete'),
    path('/complete/p/<int:domino_id>/', views.completeParent, name='completeParent'),
    path('/complete/j/<int:journey_id>/f/<int:domino_id>/', views.completeJourney, name='completeJourney'),
    path('/complete/h/<int:domino_id>/', views.completeHome, name='completeHome'),
    path('/note/<int:domino_id>/', views.newnote, name='newnote'),
    path('/time/<int:domino_id>/', views.newtime, name='newtime'),
    path('/edit/<int:domino_id>/', views.update, name='update'),
    path('/domino', views.index, name="index"),
    path('/domino/new', views.new, name="new"),
    path('/domino/new/j/<int:journey_id>/', views.newJourneyDomino, name="newJourneyDomino"),
    path('/domino/newjourney', views.newjourney, name="newjourney"),
    path('/domino/updatejourney/<int:journey_id>', views.updatejourney, name="updatejourney"),
    path('/domino/journey/<int:journey_id>', views.journey, name="journey"),
    path('/domino/delete/<int:delete_id>', views.delete, name="delete"),
    path('/domino/delete/j/<int:journey_id>/f/<int:domino_id>/', views.deleteJourneyDomino, name='deleteJourneyDomino'),
    path('/domino/id/<int:domino_id>/', views.domino, name='domino'),
    path('/domino/new/<int:domino_id>/', views.newsub, name='newsub'),
    path('/domino/pin/<int:domino_id>/', views.pin, name='pin'),
    path('/domino/pin/p/<int:domino_id>/', views.pinParent, name='pinParent'),
    path('/domino/pin/h/<int:domino_id>/', views.pinHome, name='pinHome'),
    path('/domino/pin/j/<int:journey_id>/f/<int:domino_id>/', views.pinJourney, name='pinJourney'),
    path('/domino/complete/<int:domino_id>/', views.complete, name='complete'),
    path('/domino/complete/p/<int:domino_id>/', views.completeParent, name='completeParent'),
    path('/domino/complete/j/<int:journey_id>/f/<int:domino_id>/', views.completeJourney, name='completeJourney'),
    path('/domino/complete/h/<int:domino_id>/', views.completeHome, name='completeHome'),
    path('/domino/note/<int:domino_id>/', views.newnote, name='newnote'),
    path('/domino/time/<int:domino_id>/', views.newtime, name='newtime'),
    path('/domino/edit/<int:domino_id>/', views.update, name='update'),
    path('/privacy-policy', views.privacy, name="privacy"),
    path('/register', views.register, name="register"),
    #path('/login', views.login, name="login"),  
    path('/', include("django.contrib.auth.urls"))  
]
